<div class="game_div" id="pipe_div">
    <section class="info_section">
        <div class="timer">
            <p id="time">00:00</p>
        </div>
        <div class="info_game">
            <p>Score : <span id="balls">0</span></p>
        </div>
        <div class="message_game">
            <div class="message"></div>
        </div>
    </section>
    <section class="canvas_section">
        <div id="canvas_div">
            <canvas id="canvas_background" width="<?= BOARD_W ?>" height="<?= BOARD_H ?>"></canvas>
            <canvas id="canvas_layer0" width="<?= BOARD_W ?>" height="<?= BOARD_H ?>"></canvas>
            <canvas id="canvas_layer1" width="<?= BOARD_W ?>" height="<?= BOARD_H ?>"></canvas>
            <canvas id="canvas_tooltip" width="<?= BOARD_W ?>" height="<?= BOARD_H ?>"></canvas>
        </div>
    </section>
    <section class="controls_section">
        <div class="buttons_div">
            <div id="nextPieces">
                <div class="nextPiece_div" data-id="0"></div>
                <div class="nextPiece_div" data-id="1"></div>
                <div class="nextPiece_div" data-id="2"></div>
                <div class="nextPiece_div" data-id="3"></div>
                <div class="nextPiece_div" data-id="4"></div>
                <div id="arrow"><svg width="20" height="20"><path d="M0 10 L20 0 L20 20 Z" fill="red"/></svg></div>
            </div>
            <button type="button" id="fast_button">De l'eau !</button>
        </div>
    </section>
</div>