<div class="game_div" id="pipe_div">
    <section class="info_section">
        <div class="info_game">
            <p>Niveau : <span id="level">1</span>/10</p>
            <p>Score : <span id="score">0</span></p>
            <p>Tuyaux : <span id="block">0</span>/<span id="blockMin">10</span></p>
        </div>
        <div class="message_game">
            <div class="message"></div>
        </div>
        <div>
            <button type="button" id="fast_button">Accélération</button>
            <div class="timer">
                <p id="time">00:00</p>
            </div>
        </div>
    </section>
    <section class="canvas_section">
        <div id="canvas_div">
            <canvas id="canvas_background" width="<?= BOARD_W ?>" height="<?= BOARD_H ?>"></canvas>
            <canvas id="canvas_layer0" width="<?= BOARD_W ?>" height="<?= BOARD_H ?>"></canvas>
            <canvas id="canvas_tooltip" width="<?= BOARD_W ?>" height="<?= BOARD_H ?>"></canvas>
        </div>
    </section>
    <section class="controls_section">
        <div class="buttons_div">
            <div id="tank">
                <svg width="10" height="500">
                    <rect id="tank_svg" x="0" y="0" width="10" height="0" fill="#00c3dd"/>
                </svg>
            </div>
            <div id="nextPieces">
                <div class="nextPiece_div" data-id="0"></div>
                <div class="nextPiece_div" data-id="1"></div>
                <div class="nextPiece_div" data-id="2"></div>
                <div class="nextPiece_div" data-id="3"></div>
                <div class="nextPiece_div" data-id="4"></div>
                <div id="arrow"><svg width="60" height="20"><path d="M10 0 L0 20 L20 20 Z" fill="red"/></svg></div>
            </div>
        </div>
    </section>
</div>